"""`.gitignore` generated-block management (see docs/spec/04-cli.md, ".gitignore handling")."""
from __future__ import annotations

import os

from . import importer

HEADER = "#==== GENERATED BY GIT COMPONENTS ===="
SUBHEADER = "# DO NOT MODIFY"
FOOTER = "#==== END OF COMPONENTS ===="


def read_lines(path: str) -> list[str]:
    if not os.path.isfile(path):
        return []
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read().splitlines()


def strip_generated_block(lines: list[str]) -> list[str]:
    """Remove a previously generated block (and the blank line before it), if present."""
    try:
        start = lines.index(HEADER)
    except ValueError:
        return list(lines)

    try:
        end = lines.index(FOOTER, start)
    except ValueError:
        end = len(lines) - 1

    before = lines[:start]
    while before and before[-1] == "":
        before.pop()

    after = lines[end + 1:]
    while after and after[0] == "":
        after.pop(0)

    return before + after


def _anchored(dest_path: str) -> str:
    posix = dest_path.replace(os.sep, "/")
    return posix if posix.startswith("/") else f"/{posix}"


def build_block(entries: list[tuple[str, str, str, str]]) -> list[str]:
    """entries: (component, from_, to_, dest_path) tuples, in the order to emit them."""
    lines = [HEADER, SUBHEADER, ""]
    for component, from_, to_, dest_path in entries:
        lines.append(f"# {component}@{from_}:{to_}")
        lines.append(_anchored(dest_path))
    lines.append("")
    lines.append(FOOTER)
    return lines


def write(path: str, base_lines: list[str], entries: list[tuple[str, str, str, str]]) -> None:
    lines = list(base_lines)
    if entries:
        if lines and lines[-1] != "":
            lines.append("")
        lines.extend(build_block(entries))

    if not lines:
        # nothing to say: don't create an empty .gitignore that didn't exist before
        if os.path.isfile(path):
            os.remove(path)
        return

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def entries_for(data: dict, lock_data: dict) -> list[tuple[str, str, str, str]]:
    """Reconstruct the full `.gitignore` entry list from the manifest + lock.

    Rule provenance isn't persisted in the lock (docs/spec/03-lock-format.md
    only stores a hash per file), so entries are recovered by matching each
    locked destination path back against the manifest's current import rules.
    """
    entries = []
    for name, component in data.get("components", {}).items():
        if not component.get("add-to-gitignore", True):
            continue
        locked = lock_data.get("components", {}).get(name)
        if not locked:
            continue
        for dest in locked.get("imported-files", {}):
            from_, to_ = importer.rule_for_dest(component, dest)
            entries.append((name, from_, to_, dest))
    return entries
