import os
import stat

import yaml

from gitcomponent import errors
from gitcomponent.cli import main


def _add_component(source_repo, ref="branch=main", name="mylib", extra_args=None):
    args = [
        "add", name, str(source_repo), ref,
        "--map", "src/core/:vendor/mylib/core/",
        "--exclude-glob", "**/*.md",
        "--map", "src/utils/:vendor/mylib/utils/",
        "--exclude-glob", "tests/**",
    ]
    if extra_args:
        args += extra_args
    assert main(args) == errors.EXIT_SUCCESS


def test_pull_copies_filtered_files(repo, source_repo):
    main(["init"])
    _add_component(source_repo)

    assert main(["pull"]) == errors.EXIT_SUCCESS

    assert (repo / "vendor/mylib/core/a.py").read_text() == "print('a')\n"
    assert (repo / "vendor/mylib/core/e.py").exists()
    assert not (repo / "vendor/mylib/core/b.md").exists()  # excluded
    assert (repo / "vendor/mylib/utils/c.txt").exists()
    assert not (repo / "vendor/mylib/utils/tests/d.txt").exists()  # excluded


def test_pulled_files_are_readonly(repo, source_repo):
    main(["init"])
    _add_component(source_repo)
    main(["pull"])

    path = repo / "vendor/mylib/core/a.py"
    mode = stat.S_IMODE(os.stat(path).st_mode)
    assert not (mode & stat.S_IWUSR)


def test_pull_writes_lock_with_hashes(repo, source_repo):
    main(["init"])
    _add_component(source_repo)
    main(["pull"])

    lock_data = yaml.safe_load((repo / ".git-components.lock").read_text())
    entry = lock_data["components"]["mylib"]
    assert entry["resolved-from"] == {"branch": "main"}
    assert len(entry["commit"]) == 40
    assert len(entry["imported-files"]["vendor/mylib/core/a.py"]) == 40  # sha1 hex


def test_pull_updates_gitignore(repo, source_repo):
    main(["init"])
    _add_component(source_repo)
    main(["pull"])

    gitignore = (repo / ".gitignore").read_text()
    assert "#==== GENERATED BY GIT COMPONENTS ====" in gitignore
    assert "# mylib@src/core/:vendor/mylib/core/" in gitignore
    assert "/vendor/mylib/core/a.py" in gitignore


def test_pull_preserves_manual_gitignore_entries(repo, source_repo):
    (repo / ".gitignore").write_text("/manual/entry\n")
    main(["init"])
    _add_component(source_repo)
    main(["pull"])

    gitignore = (repo / ".gitignore").read_text()
    assert "/manual/entry" in gitignore
    assert "#==== GENERATED BY GIT COMPONENTS ====" in gitignore


def test_pull_no_gitignore_flag_is_respected(repo, source_repo):
    main(["init"])
    _add_component(source_repo, extra_args=["--no-gitignore"])
    main(["pull"])

    assert not (repo / ".gitignore").exists()


def test_pull_refuses_locally_modified_files_without_force(repo, source_repo):
    main(["init"])
    _add_component(source_repo)
    main(["pull"])

    path = repo / "vendor/mylib/core/a.py"
    os.chmod(path, 0o644)
    path.write_text("tampered\n")

    assert main(["pull"]) == errors.EXIT_LOCAL_MODIFICATIONS


def test_pull_refuses_deleted_files_without_force(repo, source_repo):
    main(["init"])
    _add_component(source_repo)
    main(["pull"])

    os.chmod(repo / "vendor/mylib/core/a.py", 0o644)
    os.remove(repo / "vendor/mylib/core/a.py")

    assert main(["pull"]) == errors.EXIT_LOCAL_MODIFICATIONS


def test_pull_force_overwrites_local_modifications(repo, source_repo):
    main(["init"])
    _add_component(source_repo)
    main(["pull"])

    path = repo / "vendor/mylib/core/a.py"
    os.chmod(path, 0o644)
    path.write_text("tampered\n")

    assert main(["pull", "--force"]) == errors.EXIT_SUCCESS
    assert path.read_text() == "print('a')\n"


def test_pull_tag_resolves_to_earlier_commit(repo, source_repo):
    main(["init"])
    _add_component(source_repo, ref="tag=v1.0")
    main(["pull"])

    assert not (repo / "vendor/mylib/core/e.py").exists()  # added after the tag


def test_pull_unknown_component_fails(repo, source_repo):
    main(["init"])
    _add_component(source_repo)
    assert main(["pull", "nope"]) == errors.EXIT_COMPONENT_NOT_FOUND


def test_pull_without_manifest_fails(repo):
    assert main(["pull"]) == errors.EXIT_MANIFEST_MISSING


def test_pull_detects_manifest_lock_drift_without_flags(repo, source_repo):
    main(["init"])
    _add_component(source_repo)
    main(["pull"])

    lock_path = repo / ".git-components.lock"
    data = yaml.safe_load(lock_path.read_text())
    data["components"]["mylib"]["commit"] = "0" * 40
    lock_path.write_text(yaml.safe_dump(data, sort_keys=False))

    assert main(["pull"]) == errors.EXIT_MANIFEST_LOCK_DISAGREE
    assert main(["pull", "--update-lock"]) == errors.EXIT_SUCCESS


def test_pull_ignore_manifest_keeps_locked_commit(repo, source_repo):
    main(["init"])
    _add_component(source_repo, ref="tag=v1.0")
    main(["pull"])

    lock_path = repo / ".git-components.lock"
    original = yaml.safe_load(lock_path.read_text())

    assert main(["pull", "--ignore-manifest"]) == errors.EXIT_SUCCESS
    after = yaml.safe_load(lock_path.read_text())
    assert after["components"]["mylib"]["commit"] == original["components"]["mylib"]["commit"]
    assert not (repo / "vendor/mylib/core/e.py").exists()


def test_pull_within_component_rule_conflict_keeps_higher_priority_rule(repo, source_repo):
    main(["init"])
    main([
        "add", "mylib", str(source_repo), "branch=main",
        "--map", "src/core/a.py:dest.py",
        "--map", "src/utils/c.txt:dest.py",
    ])
    assert main(["pull"]) == errors.EXIT_SUCCESS
    assert (repo / "dest.py").read_text() == "print('a')\n"
